spring:
  redis:
    host: 192.168.201.110
    port: 6379
  thymeleaf:
    cache: false
    enabled: true
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.csp.seckill.controller.entity
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:com/csp/seckill/controller/dao/*.xml
